# Generated by Django 3.2.10 on 2022-02-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
    ]
